// app/components/project-form.tsx
"use client"

import { useState } from "react"
import { useNavigate } from "react-router"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "./ui/button"
import { Card } from "./ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "./ui/form"
import { Input } from "./ui/input"
import { Textarea } from "./ui/textarea"
import type { Project } from "../lib/types"
import { useFetcher } from "react-router"

const formSchema = z.object({
  name: z.string().min(1, "Project name is required").max(100),
  description: z.string().max(500).optional(),
})



interface ProjectFormProps {
  project?: Project
}

export function ProjectForm({ project }: ProjectFormProps = {}) {
  const navigate = useNavigate()
  const fetcher = useFetcher()
  let busy = fetcher.state !== "idle";


  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: project?.name || "",
      description: project?.description || "",
    },
  })




  return (
    <Card className="max-w-2xl mx-auto p-6 border-slate-200 shadow-sm">
      <Form {...form}>
        <fetcher.Form method="post" action={'/projects'} className="space-y-6">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Project Name</FormLabel>
                <FormControl>
                  <Input placeholder="Enter project name" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Enter project description (optional)"
                    className="resize-none min-h-[100px]"
                    {...field}
                  />
                </FormControl>
                <FormDescription>Briefly describe the purpose of this project</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="flex justify-end gap-4">
            <Button type="button" variant="outline" onClick={() => navigate(-1)}>
              Cancel
            </Button>
            <Button type="submit" disabled={busy} className="bg-primary hover:bg-primary/90">
              {busy ? "Saving..." : project ? "Update Project" : "Create Project"}
            </Button>
          </div>
        </fetcher.Form>
      </Form>
    </Card>
  )
}

// refactor/src/lib/components/steadylist/project-form.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Card } from '$lib/components/ui/card';
	import { Input } from '$lib/components/ui/input';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Label } from '$lib/components/ui/label';
	import type { Project } from '$lib/types';
	import { goto } from '$app/navigation';
	import { enhance } from '$app/forms';
	import { toast } from 'svelte-sonner';

	interface Props {
		project?: Project;
	}

	let { project }: Props = $props();

	let formData = $state({
		name: project?.name || '',
		description: project?.description || ''
	});

	let errors = $state<Record<string, string>>({});
	let isSubmitting = $state(false);

	const validateForm = () => {
		const newErrors: Record<string, string> = {};

		if (!formData.name.trim()) {
			newErrors.name = 'Project name is required';
		} else if (formData.name.length > 100) {
			newErrors.name = 'Project name must be 100 characters or less';
		}

		if (formData.description && formData.description.length > 500) {
			newErrors.description = 'Description must be 500 characters or less';
		}

		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	};

	const handleCancel = () => {
		goto('projects');
	};

	const handleSubmit = () => {
		if (!validateForm()) return;
		isSubmitting = true;
	};
</script>

<Card class="mx-auto max-w-2xl border-slate-200 p-6 shadow-sm">
	<form
		method="post"
		action="/projects"
		use:enhance={({ formData: fd }) => {
			fd.append('name', formData.name);
			fd.append('description', formData.description);
			if (project) {
				fd.append('id', project.id);
			}

			return async ({ result }) => {
				isSubmitting = false;
				if (result.type === 'success') {
					toast.success(project ? 'Project updated!' : 'Project created!');
					goto('/projects');
				} else if (result.type === 'failure') {
					toast.error('Something went wrong');
				}
			};
		}}
		onsubmit={handleSubmit}
		class="space-y-6"
	>
		<div class="space-y-2">
			<Label for="name">Project Name</Label>
			<Input
				id="name"
				name="name"
				placeholder="Enter project name"
				bind:value={formData.name}
				class={errors.name ? 'border-red-500' : ''}
			/>
			{#if errors.name}
				<p class="text-sm text-red-500">{errors.name}</p>
			{/if}
		</div>

		<div class="space-y-2">
			<Label for="description">Description</Label>
			<Textarea
				id="description"
				name="description"
				placeholder="Enter project description (optional)"
				class="min-h-[100px] resize-none {errors.description ? 'border-red-500' : ''}"
				bind:value={formData.description}
			/>
			<p class="text-muted-foreground text-sm">Briefly describe the purpose of this project</p>
			{#if errors.description}
				<p class="text-sm text-red-500">{errors.description}</p>
			{/if}
		</div>

		<div class="flex justify-end gap-4">
			<Button type="button" variant="outline" onclick={handleCancel}>Cancel</Button>
			<Button type="submit" disabled={isSubmitting} class="bg-primary hover:bg-primary/90">
				{isSubmitting ? 'Saving...' : project ? 'Update Project' : 'Create Project'}
			</Button>
		</div>
	</form>
</Card>
