// app/components/project-header.tsx
"use client";

import { useState, useEffect } from "react";
import { Link } from "react-router";
import { useNavigate } from "react-router";
import { useFetcher } from "react-router";
import { Button } from "./ui/button";
import { Edit, Plus, Sparkles, Trash2, RefreshCcw } from "lucide-react";
import { Badge } from "./ui/badge";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "./ui/alert-dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from "./ui/dropdown-menu";
import { toast } from "sonner";
import type { Project, Task } from "../lib/types";
import { formatDate } from "../lib/utils";

interface ProjectHeaderProps {
  project: Project;
}

type ProjectDeletedTask = Task & {
  projectName: string;
  projectDeleted: boolean;
};

const onDelete = async (id: string) => {
  console.log("Deleting project", id);
};

export function ProjectHeader({ project }: ProjectHeaderProps) {
  const navigate = useNavigate();
  const fetcher = useFetcher();
  const [deletedTasks, setDeletedTasks] = useState<ProjectDeletedTask[]>([]);
  const [restoredIds, setRestoredIds] = useState<string[]>([]);
  const [isHovering, setIsHovering] = useState(false);

  // Fetch deleted tasks for this project
  useEffect(() => {
    fetcher.load("/trash");
  }, [project.id]);

  // Update deleted tasks when data changes
  useEffect(() => {
    if (fetcher.data && fetcher.data.deletedTasks) {
      // Filter for deleted tasks that belong to this project
      const projectDeletedTasks = fetcher.data.deletedTasks.filter(
        (task: ProjectDeletedTask) => task.projectId === project.id
      );
      setDeletedTasks(projectDeletedTasks);
    }
  }, [fetcher.data, project.id]);

  // Handle restore action responses
  useEffect(() => {
    if (fetcher.data && fetcher.data.success) {
      toast.success(fetcher.data.message);
    }
  }, [fetcher.state]);

  const handleDelete = async () => {
    await onDelete(project.id);
    navigate("/projects");
  };

  const handleRestore = (taskId: string) => {
    setRestoredIds((prev) => [...prev, taskId]);
    fetcher.submit(
      { id: taskId, type: "task" },
      { method: "post", action: "/trash" }
    );
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-primary">{project.name}</h1>
          <p className="text-muted-foreground mt-1">
            Created on {formatDate(project.createdAt)}
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          {deletedTasks.length > 0 && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <div
                  className="inline-flex"
                  onMouseEnter={() => setIsHovering(true)}
                  onMouseLeave={() => setIsHovering(false)}
                >
                  <Button
                    variant="outline"
                    className="transition-all duration-300 border-secondary/20 text-secondary hover:bg-secondary/10 flex items-center gap-2"
                  >
                    <motion.div
                      animate={{
                        rotate: isHovering ? [0, -8, 0, 8, 0] : 0,
                        scale: isHovering ? 1.1 : 1,
                      }}
                      transition={{
                        duration: 0.5,
                        ease: "easeInOut",
                      }}
                    >
                      <Trash2 className="h-4 w-4" />
                    </motion.div>
                    <span>Trash</span>
                    <AnimatePresence>
                      <motion.div
                        initial={{ scale: 0.8, opacity: 0 }}
                        animate={{ scale: 1, opacity: 1 }}
                        transition={{
                          type: "spring",
                          stiffness: 500,
                          damping: 25,
                        }}
                      >
                        <Badge className="bg-secondary text-white ml-1 h-5 px-1.5">
                          {deletedTasks.length}
                        </Badge>
                      </motion.div>
                    </AnimatePresence>
                  </Button>
                </div>
              </DropdownMenuTrigger>

              <DropdownMenuContent align="end" className="w-72">
                <DropdownMenuLabel className="py-3 flex items-center gap-2">
                  <Trash2 className="h-4 w-4 text-secondary" />
                  <span>Deleted Tasks</span>
                </DropdownMenuLabel>
                <DropdownMenuSeparator />

                <AnimatePresence>
                  {deletedTasks.map((task, index) => (
                    <motion.div
                      key={task.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -10 }}
                      transition={{ delay: index * 0.05 }}
                    >
                      <DropdownMenuItem
                        disabled={restoredIds.includes(task.id)}
                        className="py-2 focus:bg-secondary/5"
                      >
                        <div className="flex flex-col w-full gap-1">
                          <div className="flex justify-between items-start">
                            <span className="font-medium truncate max-w-[180px]">
                              {task.title}
                            </span>
                            <Badge
                              variant="outline"
                              className={`
                                ${
                                  task.status === "todo"
                                    ? "bg-secondary/10 text-secondary border-secondary/30"
                                    : ""
                                }
                                ${
                                  task.status === "in-progress"
                                    ? "bg-amber-500/10 text-amber-500 border-amber-500/30"
                                    : ""
                                }
                                ${
                                  task.status === "blocked"
                                    ? "bg-destructive/10 text-destructive border-destructive/30"
                                    : ""
                                }
                                ${
                                  task.status === "done"
                                    ? "bg-green-500/10 text-green-500 border-green-500/30"
                                    : ""
                                }
                                text-[10px] py-0 h-5
                              `}
                            >
                              {task.status
                                .split("-")
                                .map(
                                  (word) =>
                                    word.charAt(0).toUpperCase() + word.slice(1)
                                )
                                .join(" ")}
                            </Badge>
                          </div>
                          <div className="flex justify-end mt-1">
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 text-xs p-0 px-2 hover:bg-secondary/10 hover:text-secondary"
                              disabled={restoredIds.includes(task.id)}
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                handleRestore(task.id);
                              }}
                            >
                              <motion.div
                                animate={{
                                  rotate: restoredIds.includes(task.id)
                                    ? 360
                                    : 0,
                                }}
                                transition={{ duration: 0.5 }}
                                className="mr-1"
                              >
                                <RefreshCcw className="h-3 w-3" />
                              </motion.div>
                              {restoredIds.includes(task.id)
                                ? "Restoring..."
                                : "Restore"}
                            </Button>
                          </div>
                        </div>
                      </DropdownMenuItem>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </DropdownMenuContent>
            </DropdownMenu>
          )}

          <Button className="bg-primary hover:bg-primary/90" asChild>
            <Link to={`/projects/${project.id}/tasks/new`}>
              <Plus className="mr-2 h-4 w-4" />
              Add Task
            </Link>
          </Button>

          <Button variant="outline" asChild>
            <Link to={`/projects/${project.id}/edit`}>
              <Edit className="mr-2 h-4 w-4" />
              Edit
            </Link>
          </Button>

          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button
                variant="outline"
                className="text-destructive border-destructive/20 hover:bg-destructive/10"
              >
                <Trash2 className="mr-2 h-4 w-4" />
                Delete
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                <AlertDialogDescription>
                  This will delete the project and all its tasks. This action
                  can be undone from the trash.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction
                  onClick={handleDelete}
                  className="bg-destructive text-white hover:bg-destructive/90"
                >
                  Delete
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>

      {project.description && (
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
          <p className="text-slate-700">{project.description}</p>
        </div>
      )}
    </div>
  );
}

// refactor/src/lib/components/steadylist/project-header.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Edit, Plus, Trash2, RefreshCcw } from '@lucide/svelte';
	import { Badge } from '$lib/components/ui/badge';
	import {
		AlertDialog,
		AlertDialogAction,
		AlertDialogCancel,
		AlertDialogContent,
		AlertDialogDescription,
		AlertDialogFooter,
		AlertDialogHeader,
		AlertDialogTitle,
		AlertDialogTrigger
	} from '$lib/components/ui/alert-dialog';
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuTrigger,
		DropdownMenuSeparator,
		DropdownMenuLabel
	} from '$lib/components/ui/dropdown-menu';
	import { toast } from 'svelte-sonner';
	import type { Project, Task } from '$lib/types';
	import { formatDate } from '$lib/utils';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';

	interface Props {
		project: Project;
	}

	type ProjectDeletedTask = Task & {
		projectName: string;
		projectDeleted: boolean;
	};

	let { project }: Props = $props();

	let deletedTasks = $state<ProjectDeletedTask[]>([]);
	let restoredIds = $state<string[]>([]);
	let isHovering = $state(false);

	const onDelete = async (id: string) => {
		console.log('Deleting project', id);
	};

	// Fetch deleted tasks for this project
	const fetchDeletedTasks = async () => {
		try {
			const response = await fetch('/trash');
			const data = await response.json();
			if (data.deletedTasks) {
				deletedTasks = data.deletedTasks.filter(
					(task: ProjectDeletedTask) => task.projectId === project.id
				);
			}
		} catch (error) {
			console.error('Error fetching deleted tasks:', error);
		}
	};

	const handleDelete = async () => {
		await onDelete(project.id);
		goto('/projects');
	};

	const handleRestore = async (taskId: string) => {
		restoredIds = [...restoredIds, taskId];
		try {
			const response = await fetch('/trash', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ id: taskId, type: 'task' })
			});
			const data = await response.json();
			if (data.success) {
				toast.success(data.message);
				await fetchDeletedTasks(); // Refresh the list
			}
		} catch (error) {
			console.error('Error restoring task:', error);
			toast.error('Failed to restore task');
		}
	};

	onMount(() => {
		fetchDeletedTasks();
	});
</script>

<div class="space-y-4">
	<div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
		<div>
			<h1 class="text-primary text-3xl font-bold">{project.name}</h1>
			<p class="text-muted-foreground mt-1">
				Created on {formatDate(project.createdAt)}
			</p>
		</div>

		<div class="flex flex-wrap gap-2">
			{#if deletedTasks.length > 0}
				<DropdownMenu>
					<DropdownMenuTrigger>
						<!-- svelte-ignore a11y_no_static_element_interactions -->
						<div
							class="inline-flex"
							onmouseenter={() => (isHovering = true)}
							onmouseleave={() => (isHovering = false)}
						>
							<Button
								variant="outline"
								class="border-secondary/20 text-secondary hover:bg-secondary/10 flex items-center gap-2 transition-all duration-300"
							>
								<div
									class="h-4 w-4"
									style="transform: rotate({isHovering ? '8deg' : '0deg'}); scale: {isHovering
										? 1.1
										: 1}; transition: all 0.5s ease-in-out;"
								>
									<Trash2 class="h-4 w-4" />
								</div>
								<span>Trash</span>
								<Badge class="bg-secondary ml-1 h-5 px-1.5 text-white">
									{deletedTasks.length}
								</Badge>
							</Button>
						</div>
					</DropdownMenuTrigger>

					<DropdownMenuContent align="end" class="w-72">
						<DropdownMenuLabel class="flex items-center gap-2 py-3">
							<Trash2 class="text-secondary h-4 w-4" />
							<span>Deleted Tasks</span>
						</DropdownMenuLabel>
						<DropdownMenuSeparator />

						{#each deletedTasks as task (task.id)}
							<DropdownMenuItem
								disabled={restoredIds.includes(task.id)}
								class="focus:bg-secondary/5 py-2"
							>
								<div class="flex w-full flex-col gap-1">
									<div class="flex items-start justify-between">
										<span class="max-w-[180px] truncate font-medium">
											{task.title}
										</span>
										<Badge
											variant="outline"
											class="
                        {task.status === 'todo'
												? 'bg-secondary/10 text-secondary border-secondary/30'
												: ''}
                        {task.status === 'in-progress'
												? 'border-amber-500/30 bg-amber-500/10 text-amber-500'
												: ''}
                        {task.status === 'blocked'
												? 'bg-destructive/10 text-destructive border-destructive/30'
												: ''}
                        {task.status === 'done'
												? 'border-green-500/30 bg-green-500/10 text-green-500'
												: ''}
                        h-5 py-0 text-[10px]
                      "
										>
											{task.status
												.split('-')
												.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
												.join(' ')}
										</Badge>
									</div>
									<div class="mt-1 flex justify-end">
										<Button
											variant="ghost"
											size="sm"
											class="hover:bg-secondary/10 hover:text-secondary h-7 p-0 px-2 text-xs"
											disabled={restoredIds.includes(task.id)}
											onclick={(e: MouseEvent) => {
												e.preventDefault();
												e.stopPropagation();
												handleRestore(task.id);
											}}
										>
											<div
												class="mr-1"
												style="transform: rotate({restoredIds.includes(task.id)
													? '360deg'
													: '0deg'}); transition: transform 0.5s;"
											>
												<RefreshCcw class="h-3 w-3" />
											</div>
											{restoredIds.includes(task.id) ? 'Restoring...' : 'Restore'}
										</Button>
									</div>
								</div>
							</DropdownMenuItem>
						{/each}
					</DropdownMenuContent>
				</DropdownMenu>
			{/if}

			<Button class="bg-primary hover:bg-primary/90" href="/projects/{project.id}/tasks/new">
				<Plus class="mr-2 h-4 w-4" />
				Add Task
			</Button>

			<Button variant="outline" href="/projects/{project.id}/edit">
				<Edit class="mr-2 h-4 w-4" />
				Edit
			</Button>

			<AlertDialog>
				<AlertDialogTrigger>
					<Button
						variant="outline"
						class="text-destructive border-destructive/20 hover:bg-destructive/10"
					>
						<Trash2 class="mr-2 h-4 w-4" />
						Delete
					</Button>
				</AlertDialogTrigger>
				<AlertDialogContent>
					<AlertDialogHeader>
						<AlertDialogTitle>Are you sure?</AlertDialogTitle>
						<AlertDialogDescription>
							This will delete the project and all its tasks. This action can be undone from the
							trash.
						</AlertDialogDescription>
					</AlertDialogHeader>
					<AlertDialogFooter>
						<AlertDialogCancel>Cancel</AlertDialogCancel>
						<AlertDialogAction
							onclick={handleDelete}
							class="bg-destructive hover:bg-destructive/90 text-white"
						>
							Delete
						</AlertDialogAction>
					</AlertDialogFooter>
				</AlertDialogContent>
			</AlertDialog>
		</div>
	</div>

	{#if project.description}
		<div class="rounded-lg border border-slate-200 bg-slate-50 p-4">
			<p class="text-slate-700">{project.description}</p>
		</div>
	{/if}
</div>
