// src/lib/components/steadylist/dashboard-header.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { LogOut, Menu } from '@lucide/svelte';
	import { Button } from '$lib/components/ui/button';
	import { Avatar, AvatarFallback, AvatarImage } from '$lib/components/ui/avatar';
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuTrigger
	} from '$lib/components/ui/dropdown-menu';
	import { Sheet, SheetContent, SheetTrigger } from '$lib/components/ui/sheet';
	import NotificationIndicator from '$lib/components/steadylist/notification-indicator.svelte';
	import TrashIndicator from '$lib/components/steadylist/trash-indicator.svelte';
	import MainNav from '$lib/components/steadylist/main-nav.svelte';
	import MobileNav from '$lib/components/steadylist/mobile-nav.svelte';
	import { onMount } from 'svelte';
	import { auth } from '$lib/firebaseClient';
	import { signOut } from 'firebase/auth';

	onMount(async () => {
		const response = await fetch('/trash', {
			method: 'GET',
			headers: {
				'Content-Type': 'application/json'
			}
		});
		const data = await response.json();
		deletedItems.deletedTasks = data.deletedTasks || [];
		deletedItems.deletedProjects = data.deletedProjects || [];
	});

	type User = {
		name: string;
		email: string;
		image: string | null;
	};

	// Reactive state
	let user = $state<User | null>(null);
	let deletedItems = $state({
		deletedProjects: [],
		deletedTasks: []
	});

	// Mock user data - replace with your actual auth store
	$effect(() => {
		// This would typically come from your auth store
		user = {
			name: 'User Name',
			email: 'user@example.com',
			image: null
		};
	});

	const handleSignOut = async () => {
		try {
			await signOut(auth);
			goto('/login');
		} catch (error) {
			console.error('Sign out failed:', error);
		}
	};
</script>

<header class="flex items-center justify-between py-4">
	<div class="flex items-center gap-6">
		<a href="/" class="flex items-center gap-2">
			<div class="bg-primary relative flex h-8 w-8 items-center justify-center rounded-lg">
				<span class="text-sm font-bold text-white">T</span>
			</div>
			<span class="text-primary hidden text-xl font-bold md:inline-block"> SteadyList </span>
		</a>

		<div class="hidden md:flex">
			<MainNav />
		</div>
	</div>

	<div class="flex items-center gap-4">
		<TrashIndicator
			bind:deletedTasks={deletedItems.deletedTasks}
			bind:deletedProjects={deletedItems.deletedProjects}
		/>

		<Sheet>
			<SheetTrigger
				class="ring-offset-background hover:bg-accent hover:text-accent-foreground focus-visible:ring-ring inline-flex h-10 w-10 items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 md:hidden"
			>
				<Menu class="h-5 w-5" />
				<span class="sr-only">Toggle menu</span>
			</SheetTrigger>
			<SheetContent side="left" class="w-[240px] sm:w-[300px]">
				<div class="px-2 py-6">
					<MobileNav />
				</div>
			</SheetContent>
		</Sheet>

		<DropdownMenu>
			<DropdownMenuTrigger
				class="ring-offset-background hover:bg-accent hover:text-accent-foreground focus-visible:ring-ring relative inline-flex h-10 w-10 items-center justify-center rounded-full text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50"
			>
				<Avatar>
					<AvatarImage
						src={user?.image || '/placeholder.svg?height=40&width=40'}
						alt={user?.name || 'User'}
					/>
					<AvatarFallback class="bg-primary/10 text-primary">
						{user?.name?.charAt(0) || 'U'}
					</AvatarFallback>
				</Avatar>
			</DropdownMenuTrigger>
			<DropdownMenuContent align="end">
				<DropdownMenuItem class="font-medium">
					{user?.name || 'User'}
				</DropdownMenuItem>
				<DropdownMenuItem class="text-muted-foreground text-sm">
					{user?.email || 'user@example.com'}
				</DropdownMenuItem>
				<DropdownMenuItem onclick={handleSignOut}>
					<LogOut class="mr-2 h-4 w-4" />
					Sign out
				</DropdownMenuItem>
			</DropdownMenuContent>
		</DropdownMenu>
	</div>
</header>

// app/components/dashboard-header.tsx
"use client"

import { Link } from "react-router"
import { useNavigate, useLocation } from "react-router"
import { LogOut, Menu } from "lucide-react"
import { Button } from "./ui/button"
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "./ui/dropdown-menu"
import { Sheet, SheetContent, SheetTrigger } from "./ui/sheet"
import { mockSignOut, useUser } from "../lib/auth"
import { NotificationIndicator } from "../components/notification-indicator"
import { TrashIndicator } from "../components/trash-indicator"
import { MainNav } from "../components/main-nav"
import { MobileNav } from "../components/mobile-nav"
import { useFetcher } from "react-router"
import { useEffect, useState } from "react"

export function DashboardHeader() {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useUser()
  const fetcher = useFetcher()
  const [deletedItems, setDeletedItems] = useState({ deletedProjects: [], deletedTasks: [] })

  useEffect(() => {
    // Fetch trash data when component mounts
    fetcher.load("/trash")
  }, [])

  // Update trash data when it changes
  useEffect(() => {
    if (fetcher.data) {
      setDeletedItems({
        deletedProjects: fetcher.data.deletedProjects || [],
        deletedTasks: fetcher.data.deletedTasks || []
      })
    }
  }, [fetcher.data])

  const handleSignOut = async () => {
    await mockSignOut()
    navigate("/login")
  }

  return (
    <header className="flex items-center justify-between py-4">
      <div className="flex items-center gap-6">
        <Link to="/" className="flex items-center gap-2">
          <div className="relative w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
            <span className="text-white text-sm font-bold">T</span>
          </div>
          <span className="text-xl font-bold text-primary hidden md:inline-block">SteadyList</span>
        </Link>

        <div className="hidden md:flex">
          <MainNav />
        </div>
      </div>

      <div className="flex items-center gap-4">
        <NotificationIndicator />

        <TrashIndicator
          deletedTasks={deletedItems.deletedTasks}
          deletedProjects={deletedItems.deletedProjects}
        />

        <Sheet>
          <SheetTrigger asChild className="md:hidden">
            <Button variant="ghost" size="icon" className="md:hidden">
              <Menu className="h-5 w-5" />
              <span className="sr-only">Toggle menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="w-[240px] sm:w-[300px]">
            <div className="px-2 py-6">
              <MobileNav />
            </div>
          </SheetContent>
        </Sheet>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="relative h-10 w-10 rounded-full">
              <Avatar>
                <AvatarImage src={user?.image || "/placeholder.svg?height=40&width=40"} alt={user?.name || "User"} />
                <AvatarFallback className="bg-primary/10 text-primary">{user?.name?.charAt(0) || "U"}</AvatarFallback>
              </Avatar>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem className="font-medium">{user?.name || "User"}</DropdownMenuItem>
            <DropdownMenuItem className="text-muted-foreground text-sm">
              {user?.email || "user@example.com"}
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleSignOut}>
              <LogOut className="mr-2 h-4 w-4" />
              Sign out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  )
}
