// src/lib/components/steadylist/main-nav.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { cn } from '$lib/utils';
	import { LayoutDashboard, FolderKanban } from '@lucide/svelte';

	const pathname = $derived($page.url.pathname);

	const routes = $derived([
		{
			href: '/',
			label: 'Dashboard',
			icon: LayoutDashboard,
			active: pathname === '/'
		},
		{
			href: '/projects',
			label: 'Projects',
			icon: FolderKanban,
			active: pathname === '/projects' || pathname.startsWith('/projects/')
		}
	]);
</script>

<nav class="flex items-center gap-6">
	{#each routes as route (route.href)}
		<a
			href={route.href}
			class={cn(
				'hover:text-primary flex items-center text-sm font-medium transition-colors',
				route.active ? 'text-primary' : 'text-muted-foreground'
			)}
		>
			<route.icon class="mr-2 h-4 w-4" />
			{route.label}
		</a>
	{/each}
</nav>

// app/components/main-nav.tsx
"use client";

import { Link } from "react-router";
import { useLocation } from "react-router";
import { cn } from "../lib/utils";
import { LayoutDashboard, FolderKanban, Notebook } from "lucide-react";

export function MainNav() {
  const pathname = useLocation().pathname;

  const routes = [
    {
      href: "/",
      label: "Dashboard",
      icon: LayoutDashboard,
      active: pathname === "/",
    },
    {
      href: "/projects",
      label: "Projects",
      icon: FolderKanban,
      active: pathname === "/projects" || pathname.startsWith("/projects/"),
    },
  ];

  return (
    <nav className="flex items-center gap-6">
      {routes.map((route) => (
        <Link
          key={route.href}
          to={route.href}
          className={cn(
            "flex items-center text-sm font-medium transition-colors hover:text-primary",
            route.active ? "text-primary" : "text-muted-foreground"
          )}
        >
          <route.icon className="w-4 h-4 mr-2" />
          {route.label}
        </Link>
      ))}
    </nav>
  );
}
