// src/lib/components/steadylist/task-form.svelte
<script lang="ts">
	import { Calendar, Bell } from '@lucide/svelte';
	import { format } from 'date-fns';
	import { CalendarDate, type DateValue } from '@internationalized/date';

	import * as Form from '$lib/components/ui/form';
	import { Button } from '$lib/components/ui/button';
	import { Card } from '$lib/components/ui/card';
	import { Input } from '$lib/components/ui/input';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Select, SelectContent, SelectItem, SelectTrigger } from '$lib/components/ui/select';
	import { Calendar as CalendarComponent } from '$lib/components/ui/calendar';
	import { Popover, PopoverContent, PopoverTrigger } from '$lib/components/ui/popover';
	import { Switch } from '$lib/components/ui/switch';
	import { cn } from '$lib/utils';
	import { goto } from '$app/navigation';
	import { toast } from 'svelte-sonner';

	import { taskSchema, type TaskSchema } from '$lib/schemas/task-schema';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';

	interface Props {
		data: {
			form: SuperValidated<Infer<TaskSchema>>;
			project: { id: string; name: string };
			status: string;
		};
	}

	let { data }: Props = $props();

	const form = superForm(data.form, {
		validators: zodClient(taskSchema),
		id: 'task-form'
	});

	const { form: formData, enhance } = form;

	let calendarOpen = $state(false);
	let calendarValue = $state<DateValue | undefined>(undefined);

	// Sync calendar value with form data
	$effect(() => {
		if (calendarValue) {
			$formData.dueDate = new Date(calendarValue.year, calendarValue.month - 1, calendarValue.day);
		} else {
			$formData.dueDate = undefined;
		}
	});

	// Initialize calendar value if form data has a date
	$effect(() => {
		if ($formData.dueDate && !calendarValue) {
			const date = $formData.dueDate;
			calendarValue = new CalendarDate(date.getFullYear(), date.getMonth() + 1, date.getDate());
		}
	});

	const handleCancel = () => {
		goto(`/projects/${data.project.id}`);
	};

	const getStatusLabel = (status: string) => {
		switch (status) {
			case 'in-progress':
				return 'In Progress';
			case 'todo':
				return 'To Do';
			default:
				return status.charAt(0).toUpperCase() + status.slice(1);
		}
	};
</script>

<Card class="mx-auto max-w-2xl border-slate-200 p-6 shadow-sm">
	<form method="post" use:enhance class="space-y-6">
		<!-- Task Title -->
		<Form.Field {form} name="title">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Task Title</Form.Label>
					<Input
						{...props}
						placeholder="Enter task title"
						bind:value={$formData.title}
						name={props.name}
					/>
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>

		<!-- Description -->
		<Form.Field {form} name="description">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Description</Form.Label>
					<Textarea
						{...props}
						placeholder="Enter task description (optional)"
						class="min-h-[100px] resize-none"
						bind:value={$formData.description}
						name={props.name}
					/>
				{/snippet}
			</Form.Control>
			<Form.Description>Provide details about what needs to be done</Form.Description>
			<Form.FieldErrors />
		</Form.Field>

		<!-- Due Date -->
		<Form.Field {form} name="dueDate">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Due Date</Form.Label>
					<Popover bind:open={calendarOpen}>
						<PopoverTrigger
							{...props}
							class={cn(
								'border-input bg-background ring-offset-background hover:bg-accent hover:text-accent-foreground focus-visible:ring-ring inline-flex h-10 w-full items-center justify-start rounded-md border px-3 py-2 text-sm font-normal transition-colors focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50',
								!$formData.dueDate && 'text-muted-foreground'
							)}
						>
							{$formData.dueDate ? format($formData.dueDate, 'PPP') : 'Pick a date'}
							<Calendar class="ml-auto h-4 w-4 opacity-50" />
						</PopoverTrigger>
						<PopoverContent class="w-auto p-0" align="start">
							<CalendarComponent
								bind:value={calendarValue}
								class="rounded-md border"
								name={props.name}
							/>
						</PopoverContent>
					</Popover>
				{/snippet}
			</Form.Control>
			<Form.Description>When should this task be completed?</Form.Description>
			<Form.FieldErrors />
		</Form.Field>

		<!-- Priority -->
		<Form.Field {form} name="priority">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Priority</Form.Label>
					<Select type="single" bind:value={$formData.priority} name={props.name}>
						<SelectTrigger {...props} class="w-full">
							{$formData.priority
								? $formData.priority.charAt(0).toUpperCase() + $formData.priority.slice(1)
								: 'Select priority'}
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="low">Low</SelectItem>
							<SelectItem value="medium">Medium</SelectItem>
							<SelectItem value="high">High</SelectItem>
						</SelectContent>
					</Select>
				{/snippet}
			</Form.Control>
			<Form.Description>How important is this task?</Form.Description>
			<Form.FieldErrors />
		</Form.Field>

		<div class="grid grid-cols-1 gap-6 md:grid-cols-2">
			<!-- Status -->
			<Form.Field {form} name="status">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>Status</Form.Label>
						<Select type="single" bind:value={$formData.status} name={props.name}>
							<SelectTrigger {...props} class="w-full">
								{$formData.status ? getStatusLabel($formData.status) : 'Select status'}
							</SelectTrigger>
							<SelectContent>
								<SelectItem
									value="todo"
									class={data.status === 'todo' ? 'bg-secondary/10 font-medium' : ''}
								>
									To Do {data.status === 'todo' ? '(Selected from board)' : ''}
								</SelectItem>
								<SelectItem
									value="in-progress"
									class={data.status === 'in-progress' ? 'bg-amber-500/10 font-medium' : ''}
								>
									In Progress {data.status === 'in-progress' ? '(Selected from board)' : ''}
								</SelectItem>
								<SelectItem
									value="blocked"
									class={data.status === 'blocked' ? 'bg-destructive/10 font-medium' : ''}
								>
									Blocked {data.status === 'blocked' ? '(Selected from board)' : ''}
								</SelectItem>
								<SelectItem
									value="done"
									class={data.status === 'done' ? 'bg-green-500/10 font-medium' : ''}
								>
									Done {data.status === 'done' ? '(Selected from board)' : ''}
								</SelectItem>
							</SelectContent>
						</Select>
					{/snippet}
				</Form.Control>
				<Form.Description>Current progress of the task</Form.Description>
				<Form.FieldErrors />
			</Form.Field>

			<!-- Reminder -->
			<Form.Field {form} name="reminder">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>Set Reminder</Form.Label>
						<div class="flex items-center gap-2 pt-2">
							<Switch {...props} bind:checked={$formData.reminder} name={props.name} />
							<div class="text-muted-foreground flex items-center gap-1 text-sm">
								<Bell class="h-4 w-4" />
								Remind me about this task
							</div>
						</div>
					{/snippet}
				</Form.Control>
				<Form.Description>You'll receive a notification before the due date</Form.Description>
				<Form.FieldErrors />
			</Form.Field>
		</div>

		<div class="flex justify-end gap-4">
			<Button type="button" variant="outline" onclick={handleCancel}>Cancel</Button>
			<Form.Button class="bg-primary hover:bg-primary/90">
				{data.status ? `Add to ${getStatusLabel(data.status)}` : 'Create Task'}
			</Form.Button>
		</div>
	</form>
</Card>

// app/components/task-form.tsx
"use client"

import { Link } from "react-router"
import { FormProvider } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "./ui/button"
import { Card } from "./ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "./ui/form"
import { Input } from "./ui/input"
import { Textarea } from "./ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select"
import { Calendar } from "./ui/calendar"
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover"
import { CalendarIcon, Bell } from "lucide-react"
import { format } from "date-fns"
import { cn } from "../lib/utils"
import { Switch } from "./ui/switch"
import { useFetcher } from "react-router"
import { Form as ReactRouterForm } from "react-router"
import { useEffect } from "react"



const formSchema = z.object({
  title: z.string().min(1, "Task title is required").max(100),
  description: z.string().max(500).optional(),
  dueDate: z.date().optional(),
  priority: z.enum(["low", "medium", "high"]),
  status: z.enum(["todo", "in-progress", "blocked", "done"]),
  reminder: z.boolean(),
})

interface TaskFormProps {
  projectId: string
  initialStatus?: "todo" | "in-progress" | "blocked" | "done"
}

export function TaskForm({ projectId, initialStatus }: TaskFormProps) {
  const fetcher = useFetcher()
  let busy = fetcher.state !== "idle";

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: "",
      description: "",
      dueDate: undefined,
      priority: "medium" as "low" | "medium" | "high",
      status: initialStatus || "todo" as "todo" | "in-progress" | "blocked" | "done",
      reminder: false,
    },
  })

  useEffect(() => {
    if (initialStatus) {
      form.setValue("status", initialStatus);
    }
  }, [initialStatus, form]);

  const priorityStr = form.watch("priority");
  const statusStr = form.watch("status");
  const reminderStr = form.watch("reminder") ? "true" : "false";
  const dueDateStr = (() => {
    const d = form.watch("dueDate");
    return d ? d.toISOString() : "";
  })();


  return (
    <Card className="max-w-2xl mx-auto p-6 border-slate-200 shadow-sm">
      <FormProvider {...form}>
        <ReactRouterForm
          method="post"
          action={`/projects/${projectId}/tasks`}
          className="space-y-6"
        >
          <FormField
            control={form.control}
            name="title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Task Title</FormLabel>
                <FormControl>
                  <Input placeholder="Enter task title" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Enter task description (optional)"
                    className="resize-none min-h-[100px]"
                    {...field}
                  />
                </FormControl>
                <FormDescription>Provide details about what needs to be done</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <FormField
              control={form.control}
              name="dueDate"
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>Due Date</FormLabel>
                  <Popover>
                    <PopoverTrigger asChild>
                      <FormControl>
                        <Button
                          variant="outline"
                          className={cn("w-full pl-3 text-left font-normal", !field.value && "text-muted-foreground")}
                        >
                          {field.value ? format(field.value, "PPP") : <span>Pick a date</span>}
                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                        </Button>
                      </FormControl>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar mode="single" selected={field.value} onSelect={field.onChange} initialFocus className="rounded-md border"
                      />
                    </PopoverContent>
                  </Popover>
                  <FormDescription>When should this task be completed?</FormDescription>
                  <FormMessage />
                  <input
                    type="hidden"
                    name="dueDate"
                    value={dueDateStr}
                    readOnly
                  />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="priority"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Priority</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select priority" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="low">Low</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="high">High</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormDescription>How important is this task?</FormDescription>
                  <FormMessage />
                  <input
                    type="hidden"
                    name="priority"
                    value={priorityStr}
                    readOnly
                  />
                </FormItem>
              )}
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <FormField
              control={form.control}
              name="status"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Status</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select status" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="todo" className={initialStatus === "todo" ? "bg-secondary/10 font-medium" : ""}>
                        To Do {initialStatus === "todo" && "(Selected from board)"}
                      </SelectItem>
                      <SelectItem value="in-progress" className={initialStatus === "in-progress" ? "bg-amber-500/10 font-medium" : ""}>
                        In Progress {initialStatus === "in-progress" && "(Selected from board)"}
                      </SelectItem>
                      <SelectItem value="blocked" className={initialStatus === "blocked" ? "bg-destructive/10 font-medium" : ""}>
                        Blocked {initialStatus === "blocked" && "(Selected from board)"}
                      </SelectItem>
                      <SelectItem value="done" className={initialStatus === "done" ? "bg-green-500/10 font-medium" : ""}>
                        Done {initialStatus === "done" && "(Selected from board)"}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                  <FormDescription>Current progress of the task</FormDescription>
                  <FormMessage />

                  <input
                    type="hidden"
                    name="status"
                    value={statusStr}
                    readOnly
                  />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="reminder"
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>Set Reminder</FormLabel>
                  <div className="flex items-center gap-2 pt-2">
                    <FormControl>
                      <Switch checked={field.value} onCheckedChange={field.onChange} />
                    </FormControl>
                    <div className="flex items-center gap-1 text-sm text-muted-foreground">
                      <Bell className="h-4 w-4" />
                      Remind me about this task
                    </div>
                  </div>
                  <FormDescription>You'll receive a notification before the due date</FormDescription>
                  <FormMessage />
                  <input
                    type="hidden"
                    name="reminder"
                    value={reminderStr}
                    readOnly
                  />
                </FormItem>
              )}
            />
          </div>

          <div className="flex justify-end gap-4">
            <Button type="button" variant="outline">
              <Link to={`/projects/${projectId}`}>
                Cancel
              </Link>
            </Button>
            <Button type="submit" disabled={busy} className="bg-primary hover:bg-primary/90">
              {busy ? "Saving..." : initialStatus
                ? `Add to ${initialStatus === 'in-progress' ? 'In Progress' : initialStatus.charAt(0).toUpperCase() + initialStatus.slice(1)}`
                : "Create Task"}
            </Button>
          </div>
        </ReactRouterForm>
      </FormProvider>
    </Card>
  )
}
