// app/components/dashboard-projects.tsx
"use client"

import { useEffect, useState } from "react"
import { Link } from "react-router"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card"
import { Badge } from "./ui/badge"
import { Button } from "./ui/button"
import type { Project, Task } from "../lib/types"
import { ArrowRight, Plus } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"

interface DashboardProjectsProps {
  projects: Project[]
  tasks: Task[]
}

export function DashboardProjects({ projects, tasks }: DashboardProjectsProps) {
  // Display up to 4 projects
  const displayLimit = 4

  const projectsWithCounts = projects.map((project) => {
    const activeTasks = tasks.filter((task) => !task.deleted && task.projectId === project.id)
    return {
      ...project,
      taskCount: activeTasks.length,
    }
  })

  // Get only the projects we want to display
  const visibleProjects = projectsWithCounts.slice(0, displayLimit)

  return (
    <Card className="col-span-1">
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <div>
          <CardTitle className="text-xl font-bold text-primary">Recent Projects</CardTitle>
          <CardDescription>Your most recently updated projects</CardDescription>
        </div>
        <Link to="/projects">
          <Button variant="ghost" size="sm" className="text-primary">
            View All
            <ArrowRight className="ml-1 h-4 w-4" />
          </Button>
        </Link>
      </CardHeader>
      <CardContent className="pb-2">
        {projects.length === 0 ? (
          <div className="text-center py-8">
            <p className="text-muted-foreground mb-4">No projects yet</p>
            <Link to="/projects/new">
              <Button className="bg-primary hover:bg-primary/90">
                <Plus className="mr-2 h-4 w-4" />
                Create Project
              </Button>
            </Link>
          </div>
        ) : (
          <div className="space-y-4">
            <AnimatePresence>
              {visibleProjects.map((project, index) => (
                <motion.div
                  key={project.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ delay: index * 0.05 }}
                >
                  <Link to={`/projects/${project.id}`}>
                    <div className="p-4 rounded-lg border hover:border-primary/50 hover:bg-primary/5 transition-colors cursor-pointer">
                      <div className="flex justify-between items-start mb-2">
                        <h3 className="font-medium text-primary">{project.name}</h3>
                        <div className="flex gap-2">
                          {project.taskCount > 0 && (
                            <Badge variant="outline" className="bg-secondary/10 text-secondary border-secondary/30">
                              {project.taskCount} to do
                            </Badge>
                          )}
                          {project.blockedTaskCount !== undefined && project.blockedTaskCount > 0 && (
                            <Badge variant="outline" className="bg-destructive/10 text-destructive border-destructive/30">
                              {project.blockedTaskCount} blocked
                            </Badge>
                          )}
                        </div>
                      </div>
                      {project.description && (
                        <p className="text-sm text-muted-foreground line-clamp-2 mb-2">{project.description}</p>
                      )}
                      <div className="text-sm text-muted-foreground">
                        {project.taskCount} {project.taskCount === 1 ? "task" : "tasks"}
                      </div>
                    </div>
                  </Link>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// src/lib/components/steadylist/dashboard-projects.svelte
<script lang="ts">
	import {
		Card,
		CardContent,
		CardDescription,
		CardHeader,
		CardTitle
	} from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import type { Project, Task } from '$lib/types';
	import { ArrowRight, Plus } from '@lucide/svelte';
	import { fade, fly } from 'svelte/transition';

	interface Props {
		projects: Project[];
		tasks: Task[];
	}

	let { projects, tasks }: Props = $props();

	// Display up to 4 projects
	const displayLimit = 4;

	const projectsWithCounts = $derived(
		projects.map((project) => {
			const activeTasks = tasks.filter((task) => !task.deleted && task.projectId === project.id);
			return {
				...project,
				taskCount: activeTasks.length
			};
		})
	);

	// Get only the projects we want to display
	const visibleProjects = $derived(projectsWithCounts.slice(0, displayLimit));
</script>

<Card class="col-span-1">
	<CardHeader class="flex flex-row items-center justify-between pb-2">
		<div>
			<CardTitle class="text-primary text-xl font-bold">Recent Projects</CardTitle>
			<CardDescription>Your most recently updated projects</CardDescription>
		</div>
		<a href="/projects">
			<Button variant="ghost" size="sm" class="text-primary">
				View All
				<ArrowRight class="ml-1 h-4 w-4" />
			</Button>
		</a>
	</CardHeader>
	<CardContent class="pb-2">
		{#if projects.length === 0}
			<div class="py-8 text-center">
				<p class="text-muted-foreground mb-4">No projects yet</p>
				<a href="/projects/new">
					<Button class="bg-primary hover:bg-primary/90">
						<Plus class="mr-2 h-4 w-4" />
						Create Project
					</Button>
				</a>
			</div>
		{:else}
			<div class="space-y-4">
				{#each visibleProjects as project, index (project.id)}
					<div in:fly={{ y: 10, delay: index * 50 }} out:fade={{ duration: 150 }}>
						<a href="/projects/{project.id}">
							<div
								class="hover:border-primary/50 hover:bg-primary/5 cursor-pointer rounded-lg border p-4 transition-colors"
							>
								<div class="mb-2 flex items-start justify-between">
									<h3 class="text-primary font-medium">{project.name}</h3>
									<div class="flex gap-2">
										{#if project.taskCount > 0}
											<Badge
												variant="outline"
												class="bg-secondary/10 text-secondary border-secondary/30"
											>
												{project.taskCount} to do
											</Badge>
										{/if}
										{#if project.blockedTaskCount !== undefined && project.blockedTaskCount > 0}
											<Badge
												variant="outline"
												class="bg-destructive/10 text-destructive border-destructive/30"
											>
												{project.blockedTaskCount} blocked
											</Badge>
										{/if}
									</div>
								</div>
								{#if project.description}
									<p class="text-muted-foreground mb-2 line-clamp-2 text-sm">
										{project.description}
									</p>
								{/if}
								<div class="text-muted-foreground text-sm">
									{project.taskCount}
									{project.taskCount === 1 ? 'task' : 'tasks'}
								</div>
							</div>
						</a>
					</div>
				{/each}
			</div>
		{/if}
	</CardContent>
</Card>
