// app/components/mobile-nav.tsx
"use client";

import { Link } from "react-router";
import { useLocation } from "react-router";
import { cn } from "../lib/utils";
import { Button } from "./ui/button";
import { LayoutDashboard, FolderKanban, Notebook } from "lucide-react";

export function MobileNav() {
  const pathname = useLocation().pathname;

  const routes = [
    {
      href: "/",
      label: "Dashboard",
      icon: LayoutDashboard,
      active: pathname === "/",
    },
    {
      href: "/projects",
      label: "Projects",
      icon: FolderKanban,
      active: pathname === "/projects" || pathname.startsWith("/projects/"),
    },
  ];

  return (
    <div className="flex flex-col gap-2">
      {routes.map((route) => (
        <Link key={route.href} to={route.href} className="w-full">
          <Button
            variant={route.active ? "default" : "ghost"}
            className={cn(
              "w-full justify-start",
              route.active
                ? "bg-primary text-primary-foreground"
                : "text-muted-foreground"
            )}
          >
            <route.icon className="w-4 h-4 mr-2" />
            {route.label}
          </Button>
        </Link>
      ))}
    </div>
  );
}

// src/lib/components/steadylist/mobile-nav.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { cn } from '$lib/utils';
	import { Button } from '$lib/components/ui/button';
	import { LayoutDashboard, FolderKanban, Heart } from '@lucide/svelte';

	const pathname = $derived($page.url.pathname);

	const routes = $derived([
		{
			href: '/',
			label: 'Dashboard',
			icon: LayoutDashboard,
			active: pathname === '/'
		},
		{
			href: '/projects',
			label: 'Projects',
			icon: FolderKanban,
			active: pathname === '/projects' || pathname.startsWith('/projects/')
		},
		{
			href: '/promises',
			label: 'Promises',
			icon: Heart,
			active: pathname === '/promises' || pathname.startsWith('/promises/')
		}
	]);
</script>

<div class="flex flex-col gap-2">
	{#each routes as route (route.href)}
		<a href={route.href} class="w-full">
			<Button
				variant={route.active ? 'default' : 'ghost'}
				class={cn(
					'w-full justify-start',
					route.active ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'
				)}
			>
				<route.icon class="mr-2 h-4 w-4" />
				{route.label}
			</Button>
		</a>
	{/each}
</div>
