// app/components/project-form.tsx
"use client"

import { useState } from "react"
import { useNavigate } from "react-router"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Button } from "./ui/button"
import { Card } from "./ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "./ui/form"
import { Input } from "./ui/input"
import { Textarea } from "./ui/textarea"
import type { Project } from "../lib/types"
import { useFetcher } from "react-router"

const formSchema = z.object({
  name: z.string().min(1, "Project name is required").max(100),
  description: z.string().max(500).optional(),
})



interface ProjectFormProps {
  project?: Project
}

export function ProjectForm({ project }: ProjectFormProps = {}) {
  const navigate = useNavigate()
  const fetcher = useFetcher()
  let busy = fetcher.state !== "idle";


  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: project?.name || "",
      description: project?.description || "",
    },
  })




  return (
    <Card className="max-w-2xl mx-auto p-6 border-slate-200 shadow-sm">
      <Form {...form}>
        <fetcher.Form method="post" action={'/projects'} className="space-y-6">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Project Name</FormLabel>
                <FormControl>
                  <Input placeholder="Enter project name" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="description"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Description</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Enter project description (optional)"
                    className="resize-none min-h-[100px]"
                    {...field}
                  />
                </FormControl>
                <FormDescription>Briefly describe the purpose of this project</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="flex justify-end gap-4">
            <Button type="button" variant="outline" onClick={() => navigate(-1)}>
              Cancel
            </Button>
            <Button type="submit" disabled={busy} className="bg-primary hover:bg-primary/90">
              {busy ? "Saving..." : project ? "Update Project" : "Create Project"}
            </Button>
          </div>
        </fetcher.Form>
      </Form>
    </Card>
  )
}

// src/lib/components/steadylist/project-form.svelte
<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Input } from '$lib/components/ui/input';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Button } from '$lib/components/ui/button';
	import { Card } from '$lib/components/ui/card';
	import { projectSchema, type ProjectSchema } from '$lib/schemas/project-schema';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { toast } from 'svelte-sonner';
	import { goto } from '$app/navigation';
	import type { Project } from '$lib/types';

	interface Props {
		data: { form: SuperValidated<Infer<ProjectSchema>>; project?: Project };
		isEdit?: boolean;
	}

	let { data, isEdit = false }: Props = $props();

	const form = superForm(data.form, {
		validators: zodClient(projectSchema),
		onUpdated: ({ form: f }) => {
			if (f.valid) {
				toast.success(isEdit ? 'Project updated!' : 'Project created!');
				goto('/projects');
			} else {
				toast.error('Please fix the errors in the form');
			}
		}
	});

	const { form: formData, enhance } = form;

	const handleCancel = () => {
		goto('/projects');
	};
</script>

<Card class="mx-auto max-w-2xl border-slate-200 p-6 shadow-sm">
	<form method="post" use:enhance class="space-y-6" action="/projects/new">
		<Form.Field {form} name="name">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Project Name</Form.Label>
					<Input {...props} placeholder="Enter project name" bind:value={$formData.name} />
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>

		<Form.Field {form} name="description">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Description</Form.Label>
					<Textarea
						{...props}
						placeholder="Enter project description (optional)"
						class="min-h-[100px] resize-none"
						bind:value={$formData.description}
					/>
				{/snippet}
			</Form.Control>
			<Form.Description>Briefly describe the purpose of this project</Form.Description>
			<Form.FieldErrors />
		</Form.Field>

		<div class="flex justify-end gap-4">
			<Button type="button" variant="outline" onclick={handleCancel}>Cancel</Button>
			<Form.Button class="bg-primary hover:bg-primary/90">
				{isEdit ? 'Update Project' : 'Create Project'}
			</Form.Button>
		</div>
	</form>
</Card>
